# PHP CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/language-php/

version: 2.1
jobs:
  install_mercure:
    docker:
      - image: "rastakong/mercure:v3"
    steps:
      - checkout
      - run: echo "this is the build job"
workflows:
  install:
    jobs:
      - install_mercure
