# PHP CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/language-php/

version: 2.1
jobs:
  install_mercure:
    docker:
      - image: "rastakong/mercure:v2"
    steps:
      - checkout
      - run: git -v
workflows:
  install:
    jobs:
      - install_mercure
